# Generated by Django 5.1.5 on 2025-01-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField(max_length=255)),
                ('long_description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_images/%Y/%m/')),
                ('slug', models.SlugField(blank=True, default=None, null=True, unique=True)),
                ('marketing_price', models.FloatField()),
                ('marketing_promotional_price', models.FloatField(default=0)),
                ('product_type', models.CharField(choices=[('V', 'variation'), ('S', 'simple')], default='V', max_length=1)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
