# Generated by Django 5.1.5 on 2025-01-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('V', 'variation'), ('S', 'simple')], default='S', max_length=1),
        ),
    ]
