# Generated by Django 5.1.5 on 2025-02-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='total_value',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='image',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='order',
            name='total_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
